spring:
  application:
    name: XChangePass

  datasource:
    url: jdbc:postgresql://localhost:5432/xcp
    username: admin
    password: "0000"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          format_sql: true