name: Deploy NightTrip Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Copy Project to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "." # 프로젝트의 모든 파일을 복사하도록 수정
          target: "/home/${{ secrets.PROD_USER }}/nighttrip"
          overwrite: true
          # `rsync` 대신 `scp`를 사용하여, .gitignore에 명시된 파일은 복사되지 않음

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -e  # 오류 발생 시 스크립트 중단
            
            cd /home/${{ secrets.PROD_USER }}/nighttrip  # 절대 경로로 이동
            
            # 빌드 디렉터리가 이미 존재할 경우를 대비하여 삭제
            rm -rf build
            
            # gradlew에 실행 권한 부여
            chmod +x ./gradlew
            
            # 프로젝트 빌드
            ./gradlew clean build
            
            # .jar 파일 복사 (빌드된 jar 파일이 존재할 경우만 실행)
            mkdir -p deploy
            cp build/libs/*.jar deploy/
            
            # Docker Compose 실행
            cd deploy
            docker compose down -v
            docker compose up --build -d
            
            # 사용하지 않는 이미지 삭제
            docker image prune -f
