name: Deploy NightTrip Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # 현재 워크플로 디렉토리 (최신 소스코드)를 빌드 컨텍스트로 사용
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nighttrip-backend:latest
          
      - name: Run Docker Compose on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.PROD_USER }}/nighttrip/deploy
            docker compose down -v
            docker system prune -f
            docker compose build --no-cache
            docker compose up -d
